#!/bin/sh

# isc-dhcp-server and pssh required by Prof Wilkinson's scripts
# xinetd required for Prof Rozier's scripts

apt-get update && sudo apt-get -y upgrade
apt-get -y install nmap isc-dhcp-server pssh xinetd expect
reboot

# eof

